version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_decoration_rent
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=pato
            - POSTGRES_PASSWORD=pato11
            - POSTGRES_DB=decoration_rent
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: decoration_rent
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
volumes:
    pgdata:
        driver: local